{
  "name": "safe-async-wrapper",
  "version": "0.0.2",
  "description": "Wrapper for async functions to always catch errors as first parameter of callback",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "domain": "~0.0.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/rohit-prajapati/node-safe-async-wrapper.git"
  },
  "keywords": [
    "npm",
    "node",
    "javascript",
    "safe",
    "async",
    "wrapper",
    "try",
    "catch",
    "uncaughtexception",
    "exception"
  ],
  "author": "Rohit Prajapati <rohit.prajapati.64@gmail.com>",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/rohit-prajapati/node-safe-async-wrapper/issues"
  },
  "homepage": "https://github.com/rohit-prajapati/node-safe-async-wrapper#readme"
}
